apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard-ui
  namespace: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard-ui
  template:
    metadata:
      labels:
        app: wireguard-ui
    spec:
      containers:
        - name: wireguard-ui
          image: ngoduykhanh/wireguard-ui:latest
          imagePullPolicy: Always

          env:
            - name: WGUI_USERNAME
              value: "admin"
            - name: WGUI_PASSWORD
              value: "changeme123"

            - name: WGUI_MANAGE_START
              value: "true"
            - name: WGUI_MANAGE_RESTART
              value: "true"

            - name: WGUI_WG_CONF_PATH
              value: "/etc/wireguard/wg0.conf"

          ports:
            - containerPort: 5000

          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE

          volumeMounts:
            - name: wg-config
              mountPath: /etc/wireguard
              readOnly: false

      volumes:
        - name: wg-config
          secret:
            secretName: wireguard-config
