apiVersion: v1
kind: Service
metadata:
  name: wireguard-ui
  namespace: default
spec:
  selector:
    app: wireguard-ui
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
